### PR TITLE
Fix grammar issues throughout

### PR DESCRIPTION
**Pull request by tchajed**
Mostly inserting articles where necessary, but also fixing a few awkward phrasings.

### CODE REVIEW

**Comment by tchajed** [comment]
Ping; has somebody had a chance to look at this?

**Comment by mboersma** [comment]
LGTM. Thanks!

**Comment by tchajed** [comment]
Is this ready to be merged? Anything I should do to get it ready?

**Comment by mboersma** [comment]
@keleshev I think this improves a lot of the writing on the website and should be merged.

**Comment by tchajed** [comment]
Pinging again on this, as it has been open for a while. Thanks!

**Pull request merged**
