### PR TITLE
Added reference to .Net implementation, docopt.net

### PR DESCRIPTION
**Pull request by jimmcslim**
I came across a C#/.Net implementation of docopt, figured it should probably appear on the main website.

### CODE REVIEW

**Comment by keleshev** [comment]
Great. But you also need to run `generate.py` script to update html.

**Comment by jimmcslim** [comment]
Ok, one moment...

**Comment by jimmcslim** [comment]
Ok done.

**Comment by keleshev** [comment]
Great, thanks!

**Pull request merged**
